### ISSUE TITLE
Token manager

### ISSUE THREAD

**Issue by Waiting4Ever** [CAFECA-IO/TidetimeBridge#2]
constructor:
- owner

function:
- createToken (private) (only owner)
  - name
  - symbol
  - decimal
  - chainID
  - fromContractAddress
  - userAddress
  - amount

- mintToken (only owner) (if token doesn't exist, call create)
  - name
  - symbol
  - decimal
  - chainID
  - fromContractAddress
  - userAddress
  - amount
  - transactionHash

- burnToken (only owner)
  - tokenAddress
  - amount
  - transactionHash

- getToken
  - chainID
  - fromContractAddress

- changeOwner (only owner)
  - newOwner

**Comment by Luphia** [comment]
Total 5hr Remain 1hr
